version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=bookapp
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=bookapp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:

